image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ANDROID_SDK_TOOLS: "25.2.5"

before_script:
  - export ANDROID_HOME=/Users/willy/Library/Android/sdk/
  - export PROJECT_PATH=$PWD/

stages:
  - test

unitTests:
  stage: test
  script:
    - ./gradlew test

functionalTests:
  stage: test
  script:
    - chmod +x ./wait-emulator
    - /Users/willy/Library/Android/sdk/tools/emulator -avd Nexus_5_API_22 -no-window -no-audio & ./wait-emulator
    - adb shell input keyevent 82
    - ./gradlew cAT
    - adb emu kill