# 指定全局 job 使用的 Docker Image
image: yourself.namespace/android-build:latest

# 定义全局变量
# 指定网络代理
variables:
  HTTP_PROXY: "10.211.55.6:80"
  HTTPS_PROXY: "10.211.55.6:80"

# 预先执行脚本
# 写入 gradle 配置，具体配置根据项目配置来
before_script:
  - echo -e "systemProp.https.proxyHost=docker.for.mac.localhost\nsystemProp.https.proxyPort=port\nsystemProp.http.proxyHost=docker.for.mac.localhost\nsystemProp.http.proxyPort= port\nandroid.useDeprecatedNdk=true\norg.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" > gradle.properties

# 定义任务执行阶段
# 在这里仅执行 build 任务
stages:
  - build

# build job
build:
  stage: build # 指定任务阶段
  tags: # 指定执行任务的 Runner
    - my-tag
  only: # 仅 git tag 更新时执行任务
    - tags
  script: # 任务执行脚本，执行构建脚本
    - ./gradlew --stacktrace assembleRelease
  artifacts: # 任务构建输出，指定需要保留的文件，之后可以在 GitLab Web 端下载
    paths:
      - app/build/outputs/